config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "homes#index"

	get "carted_products", to: "carted_products#index"
	
	resources :products, only: [:show, :index] do
   		resources :carted_products, except: [:index]
	end

	namespace :admin do
		resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :orderitems, only: [:index, :edit, :update, :destroy]
	end

	# post '/checkout' => "carted"
	post '/checkouts', to: "carted_products#checkouts"

	resources :checkouts,  only: [:show]
	resources :receipts, only: [:show] 

	resources :orderitems, only: [:create]

	if Rails.env.development?
    	mount LetterOpenerWeb::Engine, at: "/letter_opener"
  	end


end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :carted_products
	has_many :orderitems
	# belongs_to :admin

	validates :item_name, :price, :image, :quantity, presence: true

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			flash[:notice] = "Product successfully created"
			redirect_to admin_products_path
		else
			flash.now[:notice] = "Post not successfully created"
			render "new"
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			flash[:notice] = "Product successfully updated"
			redirect_to admin_products_path
		else
			flash.now[:notice] = "Product not successfully updated"
			render "edit"
		end
	end

	def destroy
		@product = Product.find(params[:id])
		if @product.destroy
			flash[:notice] = "Product successfully destroyed"
			redirect_to admin_products_path
		else
			flash[:notice] = "Product not successfully destroyed"
			render "index"
		end
	end

	private 
	def product_params
		params.require(:product).permit(:item_name, :price, :quantity, :image)
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @carted_product = CartedProduct.new
  end

  def show
    @carted_product = CartedProduct.new
    @product = Product.find(params[:id])
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h1> Edit Product</h1>

<%= form_for @product, url: admin_product_path(id: @product.id), method: :put do |f| %>

<%= f.label :item_name %><br>
<%= f.text_field :item_name%>

<br>
<br>

<%= f.label :price %><br>
<%= f.text_field :price %>
<br>
<br>
<%= f.label :quantity %><br>
<%= f.text_field :quantity %>

<br>
<br>

<%= f.label :image %><br>
<%= f.file_field :image %>

<br>
<br>

<%=f.submit %>

<% end %>

app/views/admin/products/index.html.erb
<h1>index</h1>

<table class="table">
	<thead>
		<tr>
			<td>Item name</td>
			<td>Product Image</td>
			<td>Price</td>
			<td>Quantity</td>
			<td>Edit</td>
			<td>Delete</td>
		</tr>
	</thead>

	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%= product.item_name %></td>
	    	<td><%= image_tag product.image, :size => "100x100" %></td>
	    	<td><%= product.price %></td>
	    	<td><%= product.quantity %></td>
	    	<td><%= link_to "Edit", edit_admin_product_path(id: product.id)%></td>
	    	<td><%= link_to "Delete", admin_product_path(id: product.id), method: :delete, data: { confirm: "are you sure?"} %></td>
	    </tr>
	    <% end %>
	</tbody>
</table>

<%= link_to 'new', new_admin_product_path %>



<div>
<%= link_to 'orderitems_index_for_admin', admin_orderitems_path %>
</div>

app/views/admin/products/new.html.erb
<h1> New Product</h1>

<%= form_for @product, url: admin_products_path, method: :post do |f| %>

<%= f.label :item_name %><br>
<%= f.text_field :item_name%>

<br>
<br>

<%= f.label :price %><br>
<%= f.text_field :price %>
<br>
<br>
<%= f.label :quantity %><br>
<%= f.text_field :quantity %>

<br>
<br>

<%= f.label :image %><br>
<%= f.file_field :image %>

<br>
<br>

<%=f.submit %>



<% end %>