config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, :controllers => { registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "homes#index"

	get "carted_products", to: "carted_products#index"
	
	resources :products, only: [:show, :index] do
   		resources :carted_products, except: [:index]
	end

	namespace :admin do
		resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
		resources :orderitems, only: [:index, :edit, :update, :destroy]
	end

	# post '/checkout' => "carted"
	post '/checkouts', to: "carted_products#checkouts"

	resources :checkouts,  only: [:show]
	resources :receipts, only: [:show] 

	resources :orderitems, only: [:create]

	if Rails.env.development?
    	mount LetterOpenerWeb::Engine, at: "/letter_opener"
  	end


end

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= notice %></div>
<% end %>
  
<% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= alert %></div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">ShoppingApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Products</a></li>
      </ul>
      
      
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#pablo">Logged in as <strong><%= current_user.email %></strong>.</a></li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li> |
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
         </ul>   
      <% end %>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="admin">
  <% if admin_signed_in? %>
      Logged in as <strong><%= current_admin.email %></strong>.
      <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <% if Admin.count == 0 %>
        <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
      <% end %>
      <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
  <body>

    <%= render 'layouts/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>